server:
  port: 8059
spring:
  application:
    name: eureka-client-ribbon-customer
eureka:
  client:
    serviceUrl:
      #服务注册中心端口号
      #这里可以填写所有的eureka服务器地址并以','分离，当前面不能注册时候,自动选择后面的进行注册，排除单点故障问题
      defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/
    ##向注册中心注册自己 (默认true)
    register-with-eureka: true
    #从eureka上获取注册信息
    fetch-registry: true
    #表示eureka client间隔多久去拉取服务注册信息，默认30秒(服务每30秒拉取信息保存本地jvm)
    registry-fetch-interval-seconds: 30
  instance:
    # 服务在eureka注册中心里Status项的默认连接,连接到SwaggerUI中,可以直接在eureka中点进当前服务的Swagger文档
    status-page-url: http://localhost:${server.port}/swagger-ui.html

