server:
  port: 8061

spring:
  application:
    name: redis
    nameText: Redis服务
    version: 1.0
  #redis通用公共配置
  redis:
    #redis数据库索引(默认为0,redis数据库默认有16个分片,这里配置具体使用的分片)
    database: 0
    #redis服务器地址
    host: localhost
    #redis服务连接端口
    port: 6379
    #redis服务器连接密码(默认为空)
    password: sunwul
    #连接超时时间
    #timeout:
    #redis连接池配置 2.0中可以使用jedis或者lettuce配置连接池
    lettuce:
      pool:
        #最大连接数(默认为8,使用负值表示没有限制)
        max-active: 8
        #最大阻塞等待时间(默认为-1,使用负值表示没有限制)
        max-wait: -1
        #最大空闲连接(默认为8)
        max-idle: 8
        #最小空闲连接(默认为0)
        min-idle: 0
  #缓存配置
  cache:
    #缓存类型 redis
    type: redis
    redis:
      #缓存超时时间,默认60000ms
      time-to-live: 1d
      #是否缓存null数据,默认false
      cache-null-values: true
      #缓存数据key是否使用前缀,默认true
      use-key-prefix: false
      #缓存数据key的前缀,开启使用前缀时有效
      key-prefix:



