server:
  port: 8091

spring:
  application:
    name: springboot-admin-server
    nameText: AdminServer
    version: 1.0
  #配置security管理账户信息
  security:
    user:
      name: sunwul
      password: 123


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/ #,http://localhost:9002/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    status-page-url: http://localhost:${server.port}
#    health-check-url-path: /actuator/health

#端点暴露
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

#启用admin日志文件执行端点
#logging:
#  file: /application.log
#  pattern:
#    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
